using System.Collections.Generic;
using Verse;

namespace RimSynapse.Factions.Models
{
    /// <summary>
    /// Extended faction tracker owned by RimSynapse-Factions.
    /// Contains goodwill history, custom natural goodwill overrides,
    /// and faction history text generated by the LLM.
    /// Stored in SynapseFactionsWorldComponent.
    /// </summary>
    public class FactionStoryTracker : IExposable
    {
        public string factionId;
        public List<GoodwillSample> goodwillHistory = new List<GoodwillSample>();
        public float goodwillIntegral;
        public int lastEventTick;

        /// <summary>Custom natural goodwill override set by world generation (random offset).</summary>
        public int? customNaturalGoodwill;
        /// <summary>Reason for the custom natural goodwill (e.g., "World generation offset").</summary>
        public string customNaturalGoodwillReason;
        /// <summary>LLM-generated historical record for this faction.</summary>
        public string factionHistory;
        /// <summary>Absolute tick when the faction history was generated.</summary>
        public long historyGeneratedTick;

        // --- Hidden Agendas ---
        public List<HiddenAgendaLog> historicalAgendas = new List<HiddenAgendaLog>();

        // --- Espionage & Fact Book ---
        public string primaryDialect;
        public Dictionary<string, float> xenotypeDemographics = new Dictionary<string, float>();
        public float medianWealth;

        // NOTE: Demographics and Macro Resources are now aggregated dynamically
        // from SettlementStoryTrackers. They are not saved directly here anymore.

        public void ExposeData()
        {
            Scribe_Values.Look(ref factionId, "factionId");
            Scribe_Collections.Look(ref goodwillHistory, "goodwillHistory", LookMode.Deep);
            Scribe_Values.Look(ref goodwillIntegral, "goodwillIntegral");
            Scribe_Values.Look(ref lastEventTick, "lastEventTick");

            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                if (goodwillHistory == null)
                    goodwillHistory = new List<GoodwillSample>();
            }

            Scribe_Values.Look(ref customNaturalGoodwill, "customNaturalGoodwill", null);
            Scribe_Values.Look(ref customNaturalGoodwillReason, "customNaturalGoodwillReason", null);
            Scribe_Values.Look(ref factionHistory, "factionHistory", null);
            Scribe_Values.Look(ref historyGeneratedTick, "historyGeneratedTick", 0L);

            Scribe_Values.Look(ref primaryDialect, "primaryDialect", null);
            Scribe_Collections.Look(ref xenotypeDemographics, "xenotypeDemographics", LookMode.Value, LookMode.Value);
            Scribe_Values.Look(ref medianWealth, "medianWealth", 0f);
            
            Scribe_Collections.Look(ref historicalAgendas, "historicalAgendas", LookMode.Deep);

            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                if (xenotypeDemographics == null) xenotypeDemographics = new Dictionary<string, float>();
                if (historicalAgendas == null) historicalAgendas = new List<HiddenAgendaLog>();
            }
        }
    }
}
